### ISSUE TITLE
请问可不可以设置保留一定数量的硬币？

### ISSUE THREAD

**Issue by Cairl** [xiaoxiunique/schedule-new#8]
我想保留50个硬币用来以后买邀请码，可不可以设置成多余50个以上的硬币才会自动去投的功能呢？

**Comment by xiaoxiunique** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoxiunique/schedule-bilibili"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 晚上6:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiaoxiunique/schedule-bilibili] 请问可不可以设置保留一定数量的硬币？ (Issue #8)





 
我想保留50个硬币用来以后买邀请码，可不可以设置成多余50个以上的硬币才会自动去投的功能呢？

**Comment by xiaoxiunique** [comment]
不过需要自己实现一下哦
